const Dept =[{
    id:1,
    title:"President",
    name:"President",
    head:"B. Lakshman",
    rollno:"1602-21-735-154",
    descrip:"",
    linkedin:"https://www.linkedin.com/in/balanakulakshman",
    gmail:"lakshmanb567@gmail.com",
    imageSource:"https://i.postimg.cc/GhnPrN7B/Lakshman-asp.jpg",
 },
 {
    id:2,
    title:"Vice President",
    name:"Vice President",
    head:"T. Mansi",
    rollno:"1602-21-735-020",
    descrip:"",
    linkedin:"https://www.linkedin.com/in/mansitalla03/",
    gmail:"mansi.talla@gmail.com",
    imageSource:"https://i.postimg.cc/SxyWY9pk/Mansi-asp.jpg",
 },
 {
    id:3,
    title:"Head of Human Resources",
    name:"Human Resources",
    head:"D. Shyam",
    rollno:"1602-21-736-304",
    descrip:"",
    linkedin:"https://www.linkedin.com/in/shyamjagadeesh/",
    gmail:"shyamdukkipati126@gmail.com",
    imageSource:"https://i.postimg.cc/sDwJzMyN/Shyam-asp.jpg",
 },
 {
    id:4,
    title:"Head of Event Management",
    name:"Event Management",
    head:"M. Anjali",
    rollno:"1602-21-735-004",
    descrip:"",
    linkedin:"https://www.linkedin.com/in/anjalimulka02/",
    gmail:"lakshmanb459@gmail.com",
    imageSource:"https://i.postimg.cc/wMkQ7vN3/Anjali-asp.jpg",
 },
 {
    id:5,
    title:"Head of Public Relations and Content",
    name:"Public Relations and Content",
    head:"T. S. Ananya",
    rollno:"1602-21-735-037",
    descrip:"",
    linkedin:"https://www.linkedin.com/in/ananya-tungaturthi/",
    gmail:"tungaturthisaiananya@gmail.com",
    imageSource:"https://i.postimg.cc/q7twj4PZ/Ananya-asp.jpg",
 },
 {
    id:6,
    title:"Head of Marketing",
    name:"Marketing",
    head:"K. Sai Krishna",
    rollno:"1602-21-735-168",
    descrip:"",
    linkedin:"https://www.linkedin.com/in/sai-krishna-kandagatla-173818249/",
    gmail:"saikrishna.kandagatla08@gmail.com",
    imageSource:"https://i.postimg.cc/8zYBFx7d/Sai-Krishna-asp.jpg",
 },
 {
    id:7,
    title:"Head of Technology",
    name:"Technology",
    head:"S. V. S. S. Kousik",
    rollno:"1602-21-735-190",
    descrip:"",
    linkedin:"https://www.linkedin.com/in/kousik-sanagavarapu/",
    gmail:"five231003@gmail.com",
    imageSource:"https://i.postimg.cc/KvZ5CPXT/Kousik-asp.jpg",
 },
 {
    id:8,
    title:"Head of Arts",
    name:"Arts",
    head:"P. Keerthana",
    rollno:"1602-21-735-017",
    descrip:"",
    linkedin:"https://www.linkedin.com/in/keerthana-prakash-b752b2288/",
    gmail:"keerthanaprakash085@gmail.com",
    imageSource:"https://i.postimg.cc/gjpKzRnf/Keerthana-asp.jpg",
 },
 {
    id:9,
    title:"Head of Arts",
    name:"Arts",
    head:"G. Eshwar",
    rollno:"1602-21-735-012",
    descrip:"",
    linkedin:"https://www.linkedin.com/in/eshwargottupalli/",
    gmail:"eshwarnagavenkat@gmail.com",
    imageSource:"https://i.postimg.cc/SQLrZZPq/Eshwar-asp.jpg",
 },
 {
    id:10,
    title:"Head of Art of Hustle",
    name:"Art of Hustle",
    head:"Y. Sai Anurag",
    rollno:"1602-21-737-009",
    descrip:"",
    linkedin:"https://www.linkedin.com/in/anurag-sai-y-6b2a18256/",
    gmail:"anuragsai2004@gmail.com",
    imageSource:"https://i.postimg.cc/hjTrRMPL/Anurag-asp.jpg",
 },
 {
    id:11,
    title:"Head of Art of Hustle",
    name:"Art of Hustle",
    head:"M. Tanish",
    rollno:"1602-22-736-075",
    descrip:"",
    linkedin:"https://www.linkedin.com/in/tanishmanem135/",
    gmail:"tani.manem@gmail.com",
    imageSource:"https://i.postimg.cc/6pqfpBp5/Tanish-asp.jpg",
 },
 ];

 export default Dept;
